# Example
storePassword=12345678
keyPassword=12345678
keyAlias=myKey
storeFile=C:\\Users\\hp\\Projects\\Remote\\Dubai\\bini\\Flutter-Music-Pro\\android\\app\\jks\\upload-keystore.jks
# storePassword=<password-from-previous-step>
# keyPassword=<password-from-previous-step>
# keyAlias=upload
# storeFile=<keystore-file-location>