# Example
storePassword=12345678
keyPassword=12345678
keyAlias=myKey
storeFile=/home/barok/Documents/Mine/zmareApp/zmare-Mobile-APP/android/app/jks/upload-keystore.jks
# storePassword=<password-from-previous-step>
# keyPassword=<password-from-previous-step>
# keyAlias=upload
# storeFile=<keystore-file-location>