# release
storePassword=miraf1
keyPassword=miraf1
keyAlias=release-key-alias
storeFile=/android/app/jks/release-keystore.jks

# debug
debugStorePassword=miraf1
debugKeyPassword=miraf1
debugKeyAlias=debug-key-alias
debugStoreFile=android/app/jks/debug-keystore.jks